FROM node:22 AS build

WORKDIR /app

COPY frontend/ ./ 

RUN npm install -g @angular/cli

RUN npm install

RUN ng build

FROM nginx:stable-alpine AS deploy

COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
