services:
  database:
    image: postgres:alpine
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    ports:
      - '4200:4200'

  core-api:
    build:
      context: .
      dockerfile: ./core-api/Dockerfile.dev
    ports:
      - '7054:7054'
    environment:
      - ASPNETCORE_ENVIRONMENT=${CORE_API_ENV}

  auth-api:
    build:
      context: .
      dockerfile: ./auth-api/Dockerfile.dev
    ports:
      - '7055:7055'
    environment:
      - ASPNETCORE_ENVIRONMENT=${AUTH_API_ENV}

volumes:
  postgres_data:
