services:
  database:
    image: postgres:alpine
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    ports:
      - '80:80'
