services:
  database:
    image: postgres:alpine
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    ports:
      - '4200:4200'

  core-api:
    build:
      context: .
      dockerfile: ./core-api/Dockerfile.dev
    ports:
      - '7054:7054'
    environment:
      - ASPNETCORE_ENVIRONMENT=${CORE_API_ENV}
      - FRONTEND_URL=${FRONTEND_URL}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
    volumes:
      - ./certs:/https:ro
