FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY core-api/*.csproj ./

COPY core-api/ ./

RUN dotnet restore

EXPOSE 7054

CMD ["dotnet", "run", "--urls", "https://host.docker.internal:7054"]