# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src/auth-api

COPY auth-api/*.csproj ./

RUN dotnet restore

COPY auth-api/ ./

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

COPY --from=build /app ./

ENV ASPNETCORE_URLS="https://+:7055" \
    ASPNETCORE_HTTPS_PORT=7055

EXPOSE 7055

ENTRYPOINT ["dotnet", "auth-api.dll"]
