FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY auth-api/*.csproj ./

COPY auth-api/ ./

RUN dotnet restore

EXPOSE 7055

CMD ["dotnet", "run", "--urls", "http://host.docker.internal:7055"]