name: Dotnet core-api build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        working-directory: ./core-api
        run: dotnet restore
      - name: Build
        working-directory: ./core-api
        run: dotnet build --no-restore
      - name: Test
        working-directory: ./core-api
        run: dotnet test --no-build --verbosity normal
